### ISSUE TITLE
import Zara

### ISSUE THREAD

**Issue by aboosamah94** [vagrod/zara#2]
Hello
hope you good and healthy
Thanks for this project
- problem happened after import "ZARA" all of Materials be pink and I have to change it to standard to let it show again

**Comment by vagrod** [comment]
Hi! Do you mean after opening Unity demo project?

**Comment by aboosamah94** [comment]
when I import it "zara" to any project or start with then add project assets all of materials be pink

**Comment by vagrod** [comment]
You don't have to import asset in order to use Zara. Unity asset is a "Template System" asset that only delivers Zara Unity Demo for you to look at. To include Zara into your project, you only need to copy "Zara" folder from it, or use "Releases" page here on github, as described in a Readme.md of this repo. Then you can navigate online wiki or offline pdf documentation to get started -- or look into Unity demo project.
What you describing is more Unity asset import bug, and not related to the survival engine itself. You can ask on Unity forums for the possible solutions on Unity asset importing issues.
